### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by jjmg84** [menkhus/nvd2mysqlloader#4]
hi!!

Great job i are tying to use with pyton3 and mariadb (with mysql connector) and i get these errors:

root@srv:~/nvd2mysql# python3 nvd2mysqlloader.py -a
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mysql/connector/cursor.py", line 569, in execute
    self._handle_result(self._connection.cmd_query(stmt))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 556, in cmd_query
    raise errors.InterfaceError(
mysql.connector.errors.InterfaceError: Use cmd_query_iter for statements with multiple queries.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/nvd2mysql/nvd2mysqlloader.py", line 577, in <module>
    main()
  File "/root/nvd2mysql/nvd2mysqlloader.py", line 561, in main
    setup_database(db,user,password)
  File "/root/nvd2mysql/nvd2mysqlloader.py", line 391, in setup_database
    curs.execute(nvd_schema)
  File "/usr/lib/python3/dist-packages/mysql/connector/cursor.py", line 572, in execute
    raise errors.InterfaceError(
mysql.connector.errors.InterfaceError: Use multi=True when executing multiple statements
root@srv:~/nvd2mysql#

Any idea what is happening? 

Thanks in advance

**Comment by menkhus** [comment]
Sorry,  I have been taking care of family.  I'll update the project, with the more current python, libraries and CVE information sources and push out a new version.

This should take a few weeks.

Best,
Mark

**Comment by menkhus** [comment]
Hi, This project uses the old NIST NVD connectors. I will learn how to decommission this project and then put a newer set of tools up here.
